<?php
return [
    'admin_user' => '{{environments_ADMIN_USER}}',
    'admin_password' => '{{environments_ADMIN_PASSWORD}}',

    'discovery_url' => '{{eureka_client_serviceUrl_defaultZone}}',
    'budgets_url' => '{{environments_BUDGETS_URL}}',
    'tenders_url' => '{{environments_TENDERS_URL}}',
    'tenders_prz_url' => '{{environments_TENDERS_PRZ_URL}}',
    'plans_prz_url' => '{{environments_PLANS_PRZ_URL}}',
    'contracts_prz_url' => '{{environments_CONTRACTS_PRZ_URL}}',
    'complaints_url' => '{{environments_COMPLAINTS_URL}}',
    'decisions_url' => '{{environments_DECISIONS_URL}}',

    'elastic_indexing' => '{{environments_ELASTIC_INDEXING}}',
    'elastic_budgets_index' => '{{environments_ELASTIC_BUDGETS_INDEX}}',
    'elastic_budgets_type' => '{{environments_ELASTIC_BUDGETS_TYPE}}',
    'elastic_tenders_index' => '{{environments_ELASTIC_TENDERS_INDEX}}',
    'elastic_tenders_type' => '{{environments_ELASTIC_TENDERS_TYPE}}',
    'elastic_plans_index' => '{{environments_ELASTIC_PLANS_INDEX}}',
    'elastic_plans_type' => '{{environments_ELASTIC_PLANS_TYPE}}',
    'elastic_contracts_index' => '{{environments_ELASTIC_CONTRACTS_INDEX}}',
    'elastic_contracts_type' => '{{environments_ELASTIC_CONTRACTS_TYPE}}',
    'elastic_cpv_index' => '{{environments_ELASTIC_CPV_INDEX}}',
    'elastic_cpv_type' => '{{environments_ELASTIC_CPV_TYPE}}',
    'elastic_proceedings_index' => '{{environments_ELASTIC_PROCEEDINGS_INDEX}}',
    'elastic_proceedings_type' => '{{environments_ELASTIC_PROCEEDINGS_TYPE}}',
    'elastic_complaints_index' => '{{environments_ELASTIC_COMPLAINTS_INDEX}}',
    'elastic_complaints_type' => '{{environments_ELASTIC_COMPLAINTS_TYPE}}',
    'elastic_decisions_index' => '{{environments_ELASTIC_DECISIONS_INDEX}}',
    'elastic_decisions_type' => '{{environments_ELASTIC_DECISIONS_TYPE}}',
    'elastic_url' => '{{environments_ELASTIC_URL}}',

    'sleep_delay_interval' => '{{environments_SLEEP_DELAY_INTERVAL}}',
    'sleep_error_interval' => '{{environments_SLEEP_ERROR_INTERVAL}}',
];
